#!/usr/bin/python3

# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import os
import string


def main():
  parser = argparse.ArgumentParser()
  parser.add_argument('template')
  parser.add_argument('output')
  args = parser.parse_args()

  with open(args.template, mode='rt') as template_file:
    template = template_file.read()
  output = string.Template(template).substitute(
      HOME=os.path.expanduser('~'),
      REPO_ROOT=os.path.abspath(os.path.dirname(__file__)),
      XDG_CACHE_HOME=os.environ.get('XDG_CACHE_HOME',
                                    os.path.expanduser('~/.cache')),
  )
  with open(args.output, mode='wt') as output_file:
    output_file.write(output)


if __name__ == '__main__':
  main()
