#!/bin/bash

# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


set -e
shopt -s nullglob


temp_dir="$(mktemp -d)"
patch_dir="$(dirname "$0")/patches"

curl https://docs.projectcalico.org/manifests/calico.yaml \
  -o "${temp_dir}/calico.yaml"
for patch in "$patch_dir"/*.patch; do
  patch --silent -d "$temp_dir" < "$patch"
done
cat "${temp_dir}/calico.yaml"

rm -rf "$temp_dir"
