#!/usr/bin/env python3

# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import re


def main():
    with open('boot/grub/grub.cfg', mode='r+t') as grub_cfg_file:
        grub_cfg = grub_cfg_file.read()
        grub_cfg_file.seek(0)
        grub_cfg_file.truncate()
        grub_cfg_file.write(
            re.sub(
                r"menuentry.*'Install'.*{((.|\n)*?) ---((.|\n)*?)}",
                (r"\g<0>\nmenuentry 'Preseed install' {\1 "
                 r"auto=true file=/cdrom/preseed.cfg "
                 r"---\3}"),
                grub_cfg,
            ))
    with open('isolinux/txt.cfg', mode='r+t') as isolinux_cfg_file:
        install_label = isolinux_cfg_file.read()
        isolinux_cfg_file.write(install_label  #
                                .replace('label install', 'label preseed')  #
                                .replace('^Install', 'Preseed install')  #
                                .replace(
                                    '---',
                                    'auto=true file=/cdrom/preseed.cfg ---'))


if __name__ == '__main__':
    main()
